import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/NavBar";
import { ThemeProvider } from "./theme/ThemeProvider";
import { Toaster as SonnarToaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <SonnarToaster />
          <NavBar />
          <div className="relative">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
